baseURL = 'http://ads.cz/'
languageCode = 'cs'
title = 'ADS'
uglyURLs = "false"
enableEmoji = "true"
buildFuture = "true"
[params]
    description = "Oficiální webové stránky Autonomního debatního spolku"
[menus]
    [[menu.main]]
        identifier = "aktuality"
        name = "Aktuality"
        url = "/aktuality/"
        weight = "1"
    [[menu.main]]
        identifier = "kalendar"
        name = "Kalendář"
        url = "/kalendar/"
        weight = "2"
    [[menu.main]]
        identifier = "kontakt"
        name = "Kontakt"
        url = "/kontakt/"
        weight = "3"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true