baseURL = 'http://ads.cz/'
languageCode = 'cz-cs'
title = 'Autonomní debatní spolek'
uglyURLs = "false"
enableEmoji = "true"
buildFuture = "true"
[params]
    description = "Oficiální webové stránky Autonomního debatního spolku"
[menus]
    [[menu.main]]
        identifier = "about"
        name = "O ADS"
        url = "/about/"
        weight = "1"
    [[menu.main]]
        identifier = "aktuality"
        name = "Aktuality"
        url = "/aktuality/"
        weight = "2"
    [[menu.main]]
        identifier = "debaty"
        name = "Debaty"
        url = "/debaty/"
        weight = "3"
    [[menu.main]]
        identifier = "kontakt"
        name = "Kontakt"
        url = "/kontakt/"
        weight = "4"
